### ISSUE TITLE
Showcase project?

### ISSUE THREAD

**Issue by ORESoftware** [janestreet/async#18]
I assume that Jane Street has servers that use the async lib?

Is there not some showcase repo on Github that shows a simple HTTP server that uses this lib?

I am looking for some skeleton I can clone to get started with the lib.

**Comment by seliopou** [comment]
You can find several examples in the [example/](https://github.com/janestreet/async/tree/master/example) subdirectory of the project. In particular [server.ml](https://github.com/janestreet/async/blob/master/example/server.ml) may be of interest to you
