### ISSUE TITLE
Wrong github link in https://opensource.janestreet.com/async/

### ISSUE THREAD

**Issue by ryuheechul** [janestreet/async#19]
`GITHUB` link in https://opensource.janestreet.com/async/ links to https://github.com/janestreet/incremental which is wrong.
I didn't know where to file this issue since I couldn't find the source repository for https://opensource.janestreet.com/async/, therefore I opened the issue here.

**Comment by seliopou** [comment]
Thanks for reporting the bad link. This will be fixed shortly.

**Comment by seliopou** [comment]
Done. Thanks again!
