### ISSUE TITLE
Unexpected behaviour change by just opening Async

### ISSUE THREAD

**Issue by renald** [janestreet/async#20]
Probably very good to explain, but takes me quite by surprise. 

I've got the following code:

In `bin/main.ml`:

````
let dummy_parser html = print_endline ("I got: >\n" ^ html)

let () =
  if Array.length Sys.argv < 2 then begin
    prerr_endline "Usage: scraper <name>";
    exit 2;
  end; (* if *)
  print_endline "here 1";
  Scraper.scrape_page Sys.argv.(1) dummy_parser`
````
And in `lib/scraper.ml`

````
let scrape_page address html_parser =
  print_endline "Hello?";
  html_parser (address ^ "je!")
````

after `dune exec scraper xyz` I get (as expected):

````
$ dune exec scraper xyz 
here 1
Hello?
I got: >
xyzje!
````

However, if I add `open Async` to `lib/scraper.ml`:
````
open Async

let scrape_page address html_parser =
  print_endline "Hello?";
  html_parser (address ^ "je!")
````

then I get:

````
$ dune exec scraper xyz 
here 1
I got: >
xyzje!
````

So, the `Hello?` is not printed.

Probably some optimization is going on, but I still am confused.

**Comment by adamyi** [comment]
`print_endline` is shadowed by https://github.com/janestreet/async_unix/blob/master/src/async_print.mli
Internally it writes to an Async writer. This is non-blocking and requires Async scheduler to be running. Your `bin/main.ml` does not start the async scheduler.

**Comment by renald** [comment]
Ah! So simple... Thanks!
