### ISSUE TITLE
Any idea to make async requests a litter slower?

### ISSUE THREAD

**Issue by liweijian** [janestreet/async#7]
I know this may sound a ridiculous question but here goes....I want to make async a littler slower.

The function which sends requests is like:

```ocaml
let map_nest alist blist fn =
  Deferred.all(
  List.fold
    alist
    ~init:[]
    ~f:(fun acc a ->
        acc @ (List.map blist ~f:(fun b -> fn a b))))
```

I need to combine the parameters from `alist` and `blist`, and send the request by `fn` (I use `Cohttp_async.Client.post` in this case).

It's too fast that the proxy server/web server can not handle so many requests at the same time, and the exception is `Connection reset by peer`

```scheme
(((pid 17915) (thread_id 0))
 ((human_readable 2016-07-06T15:09:27+0800)
  (int63_ns_since_epoch 1467788967189462000))
 "unhandled exception in Async scheduler"
 ("unhandled exception"
  ((src/monitor.ml.Error_
    ((exn
      (Unix.Unix_error "Connection reset by peer" connect 127.0.0.1:8080))
     (backtrace
      ("Raised by primitive operation at file \"src/unix_syscalls.ml\", line 863, characters 17-74"
       "Called from file \"src/deferred1.ml\", line 14, characters 63-68"
       "Called from file \"src/job_queue.ml\", line 160, characters 6-47" ""))
     (monitor
      (((name Tcp.close_sock_on_error) (here ()) (id 197)
        (has_seen_error true) (is_detached true))))))
   ((pid 17915) (thread_id 0)))))
```

I was wondering if maybe we could make async a little slower? For example, can we `sleep` for a second inside each elements of `List.fold` above?

PS: I'd tried to implement a **sleepy** version of `fold` as 
```ocaml
let rec fold_sleep f acc l =
  match l with
    [] -> acc
  | x :: xs ->  after (sec 1.0) >>= fun () -> (fold_sleep f (f acc x) xs)
```

But it does not work as expected in this demo function
```ocaml
let _ = 
   fold_sleep
      (fun acc a -> acc @ a)
      []
      [ [delayed 0.5 "hello"; delayed 1. "world"; delayed 1.5 "!"];
        [delayed 1.5 "ello"; delayed 1. "orld"; delayed 0.5 "!"];
        [delayed 0.5 "lo"; delayed 1. "ld"; delayed 2.5 "!"]
      ]
```

**Comment by diml** [comment]
> I was wondering if maybe we could make async a little slower? For example, can we sleep for a second inside each elements of List.fold above?

Yes, you can do this:

```ocaml
Deferred.List.fold alist ~init:[] ~f:(fun acc a -> after (sec 1.) >>= fun () -> ...)
```

> But it does not work as expected in this demo function

Could you explain what is the expected behavior and what you are getting instead?

**Comment by bmillwood** [comment]
I'd need to see the definition of `delayed` to know what is going on in your example, but my guess is you probably want to use ``Deferred.List.map ~how:`Sequential``, instead of running all the functions upfront and just waiting for their return deferreds.

In any case, I don't think there's a bug in async here. If you want help using the library, you're probably better off talking to [the ocaml-core google group](https://groups.google.com/forum/#!forum/ocaml-core)
