### ISSUE TITLE
Process.collect_output_and_wait throws an exception

### ISSUE THREAD

**Issue by barkmadley** [janestreet/async#8]
I have the following example code extracted from a simple script I am trying to convert to OCaml:

``` ocaml
open Core.Std
open Async.Std

let prog = "ssh"
let args = [ "server"; "--"; "cat"; "afile"; ]

let main () =
  Process.create ~prog ~args () >>= fun proc ->
  let proc = Or_error.ok_exn proc in (* assume the process was created successfully *)
  Process.collect_output_and_wait proc >>= fun output ->
  if output.Process.Output.exit_status = Result.Ok () then begin
    Print.printf "=Ok====\n%s\n=Ok====\n" output.Process.Output.stdout;
    return (Ok output.Process.Output.stdout)
  end else begin
    Print.printf "=Error=\n%s\n=Error=\n" output.Process.Output.stderr;
    return (Or_error.error_string output.Process.Output.stderr)
  end >>= fun e ->
  exit 0

let () = main (); never_returns (Scheduler.go ())
```

If the ssh command succeeds, then the standard output is printed to the terminal no problem.

If I turn the wifi off on my laptop, when I execute this code, the `Process.collect_output_and_wait` function throws an exception due to non-zero return code from ssh:

```sexp
(((pid 7718) (thread_id 0))
 ((human_readable 2016-12-30T15:48:55+1100)
  (int63_ns_since_epoch 1483073335496662000))
 "unhandled exception in Async scheduler"
 ("unhandled exception"
  ((src/monitor.ml.Error_
    ((exn
      "ssh: connect to host server port 22: Network is unreachable\r\n")
     (backtrace
      ("Raised at file \"src/error.ml\" (inlined), line 7, characters 14-30"
       "Called from file \"src/or_error.ml\", line 67, characters 17-32"
       "Called from file \"src/test.ml\", line 72, characters 17-39"
       "Called from file \"src/deferred1.ml\", line 14, characters 63-68"
       "Called from file \"src/job_queue.ml\", line 160, characters 6-47" ""))
     (monitor
      (((name main) (here ()) (id 1) (has_seen_error true)
        (is_detached false))))))
   ((pid 7718) (thread_id 0)))))
```
I found this to be surprising behaviour because the exit status is part of the `Process.Output.t` record information, presumably so that I can handle different exit status codes explicitly in my application code.

Can you confirm that this is expected behaviour, or is there something else going on?

**Comment by barkmadley** [comment]
Actually the problem appears to be that I haven't wrapped the main function into a `try_with` call.

If I do that, then the output is processed as expected. I will close this issue in favour of one dealing with `Deferred.return (Or_error.error_string "")` throwing an exception.

**Comment by barkmadley** [comment]
Actually nope. I had a stray `ok_exn` function call I forgot about and had not tested properly. My bad.

**Comment by diml** [comment]
Is this issue sorted in the end?

**Comment by barkmadley** [comment]
Yes. Sorry for the spam.
